### ISSUE TITLE
White pixels or near white pixels don't show up

### ISSUE THREAD

**Issue by lianhuilui** [nainghtetlinn/project-ascii-art-converter#1]
Given this input
![patrick](https://github.com/nainghtetlinn/project-ascii-art-converter/assets/2843170/6ee16d79-8e3c-49dd-adc1-1775a64a6c5f)

We get this scary picture
![result](https://github.com/nainghtetlinn/project-ascii-art-converter/assets/2843170/e6e022b1-3a24-4c1d-a6d9-2149c17b0f67)

**Comment by nainghtetlinn** [comment]
This could be due to the image's resolution is too low or the fact that the average color of that 5x5 pixel area is black. This can be fixed by adding the resolution slider range (1 to 35), currently it is (5 to 35).

**Comment by lianhuilui** [comment]
I think it's an actual bug.
Check out this gradient

![gradient](https://github.com/nainghtetlinn/project-ascii-art-converter/assets/2843170/9d5395c3-5b0c-4915-86cd-5e18d641e9c3)

And output
![ascii1699375337604](https://github.com/nainghtetlinn/project-ascii-art-converter/assets/2843170/87d6656f-d953-4b5f-979e-0ad0df155815)

**Comment by nainghtetlinn** [comment]
Thanks, I found it. It is because of my convertToSymbol function which takes number between 0 to 255 and return a symbol. So when the background color is white, it return empty string. This bug was fixed by adding - 1 to my density length.

**Comment by lianhuilui** [comment]
Seems okay for most, but there is one weird bug I can't describe. You can see the two "holes" in the eye.
![bug](https://github.com/nainghtetlinn/project-ascii-art-converter/assets/2843170/ad960c18-2356-4158-a143-81b62baf8716)

To reproduce:
1. use the same patrick picture from first comment
2. set background to red
3. use this character "▀" instead of "a" to promiently show the error

**Comment by nainghtetlinn** [comment]
Thanks again. I fixed it.
