### ISSUE TITLE
Every convert takes one second. Even on a PC with powerful CPU :)

### ISSUE THREAD

**Issue by lianhuilui** [nainghtetlinn/project-ascii-art-converter#2]

**Comment by nainghtetlinn** [comment]
Yes it is. I did it on purpose as I want to show loading icon in button for a second. You can see it in src/main.ts file.

**Comment by lianhuilui** [comment]
Yes, I see a timeout of 1000ms. I think it makes the app feel slower than it is.

If you really want to improve performance, there are improvements you can make in your algorithm. I can suggest a few

**Comment by nainghtetlinn** [comment]
I'm happy to hear suggestions from you.
